Repository MacMat01/cards-object-detection, pull requests merged in 2024-06, with the labels that each got.

#14 Create codeql.yml
  .github/workflows/codeql.yml
  .github/workflows/versioning.yml
Labels: enhancement

#22 Added CodeQL status badge
  README.md
Labels: documentation

#26 Data extraction/cards extraction
  src/main/python/app/real_time_app.py
  src/main/python/app/util/query_api.py
Labels: data

#29 Path fixing
  src/main/python/dataset_creation/test_hull.py
Labels: bug, dataset

#33 Updated README.md
  README.md
Labels: documentation

#31 Data extraction/round manager
  .github/workflows/codeql.yml
  README.md
  src/main/python/app/card_detection_app.py
  src/main/python/app/manager/__init__.py
  src/main/python/app/manager/card_manager.py
  src/main/python/app/manager/influxdb_manager.py
  src/main/python/app/manager/player_manager.py
  src/main/python/app/manager/video_capture_manager.py
  src/main/python/app/manager/yolo_model_manager.py
  src/main/python/app/real_time_app.py
  src/main/python/app/util/query_api.py
  src/main/python/app/video_app.py
  src/main/python/model_training/Cards Object Detection - YOLOv8.ipynb
Labels: bug, documentation, enhancement, data

#38 Patch
  README.md
  setup.py
Labels: documentation
